# Generated by Django 5.2.10 on 2026-01-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scenarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(blank=True, default='', max_length=128)),
                ('ai_mode', models.CharField(choices=[('strict', 'Strict'), ('balanced', 'Balanced'), ('free', 'Free')], default='balanced', max_length=16)),
                ('prompt', models.TextField()),
                ('result', models.TextField()),
                ('params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['scenario', 'created_at'], name='ai_aigenera_scenari_e612ac_idx'), models.Index(fields=['user', 'created_at'], name='ai_aigenera_user_id_bda46c_idx')],
            },
        ),
    ]
