# Generated by Django 5.2.10 on 2026-01-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('scenarios', '0003_scenario_goal_scenario_grade_scenario_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('daily_limit_per_user', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('generation_enabled', models.BooleanField(default=True, help_text='Глобально включает/выключает генерацию план-конспекта (экономия бюджета).')),
                ('daily_generations_per_user', models.PositiveIntegerField(default=10, help_text='Лимит генераций на одного пользователя в сутки. 0 = запрет всем (кроме staff/superuser при bypass).')),
                ('bypass_limit_for_staff', models.BooleanField(default=True, help_text='Разрешить staff/superuser игнорировать лимиты и выключатель.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Settings',
                'verbose_name_plural': 'AI Settings',
            },
        ),
        migrations.CreateModel(
            name='AIGenerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_chars', models.PositiveIntegerField(default=0)),
                ('output_chars', models.PositiveIntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_aigenera_user_id_4a55cc_idx'), models.Index(fields=['created_at'], name='ai_aigenera_created_2d2c47_idx')],
            },
        ),
    ]
