# Generated by Django 5.2.10 on 2026-01-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('emotionality', models.CharField(choices=[('calm', 'Спокойная и собранная'), ('moderate', 'Умеренно активная'), ('very_active', 'Очень активная и энергичная'), ('tires_fast', 'Быстро утомляемая'), ('anxious', 'Тревожная / неуверенная'), ('disconnected', 'Разобщённая / требует вовлечения')], default='moderate', max_length=16)),
                ('day_time', models.CharField(choices=[('begin', 'Начало дня'), ('middle', 'Середина дня'), ('end', 'Конец дня')], default='middle', max_length=16)),
                ('group_size', models.PositiveSmallIntegerField(default=0)),
                ('duration_min', models.PositiveSmallIntegerField(default=45)),
                ('teacher_notes', models.TextField(blank=True, default='')),
                ('subject_content', models.TextField(blank=True, default='')),
                ('plan_text', models.TextField(blank=True, default='')),
                ('ai_mode', models.CharField(choices=[('strict', 'Strict'), ('balanced', 'Balanced'), ('free', 'Free')], default='balanced', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scenarios.scenario')),
                ('technique_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_items', to='cards.techniquecard')),
            ],
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['owner', 'name'], name='scenarios_s_owner_i_f7921c_idx'),
        ),
        migrations.AddIndex(
            model_name='scenarioitem',
            index=models.Index(fields=['scenario', 'position'], name='scenarios_s_scenari_a49312_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenarioitem',
            constraint=models.UniqueConstraint(fields=('scenario', 'position'), name='uniq_scenario_position'),
        ),
    ]
