# Generated by Django 5.2.10 on 2026-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_default_constraint_and_custom_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='goal',
            field=models.TextField(blank=True, help_text='Цель занятия (свободный текст)', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Номер класса (например: 5, 7, 10)', null=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='subject',
            field=models.CharField(blank=True, help_text='Учебный предмет (например: Математика)', max_length=128, null=True),
        ),
    ]
