# Generated by Django 5.2.10 on 2026-01-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description_html', models.TextField()),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('age_a1', models.BooleanField(default=False)),
                ('age_a2', models.BooleanField(default=False)),
                ('age_a3', models.BooleanField(default=False)),
                ('activity_type', models.CharField(choices=[('active', 'Активная'), ('calm', 'Спокойная')], max_length=16)),
                ('work_individual', models.BooleanField(default=False)),
                ('work_group', models.BooleanField(default=False)),
                ('bloom_level', models.CharField(choices=[('remember', 'Запоминание'), ('understand', 'Понимание'), ('apply', 'Применение'), ('analyze', 'Анализ'), ('evaluate', 'Оценка'), ('create', 'Создание')], max_length=16)),
                ('k_critical', models.BooleanField(default=False)),
                ('k_creative', models.BooleanField(default=False)),
                ('k_communication', models.BooleanField(default=False)),
                ('k_collaboration', models.BooleanField(default=False)),
                ('stage_start', models.BooleanField(default=False)),
                ('stage_core', models.BooleanField(default=False)),
                ('stage_final', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Черновик (личная)'), ('pending', 'На модерации'), ('rejected', 'Отклонена'), ('public', 'Публичная'), ('archived', 'В архиве')], default='draft', max_length=16)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards_authored', to=settings.AUTH_USER_MODEL)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_moderated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'title'], name='cards_techn_status_a0fa70_idx'), models.Index(fields=['author', 'status'], name='cards_techn_author__95fb4b_idx'), models.Index(fields=['title'], name='cards_techn_title_959d4e_idx')],
            },
        ),
    ]
