# Generated by Django 5.2.10 on 2026-01-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_techniquecard_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniquecard',
            name='card_kind',
            field=models.CharField(choices=[('technique', 'Методика'), ('aux_team_split', 'Вспомогательная: деление на команды'), ('aux_warmup', 'Вспомогательная: разминка'), ('aux_org', 'Вспомогательная: оргмомент'), ('aux_reflection', 'Вспомогательная: рефлексия')], db_index=True, default='technique', max_length=32),
        ),
    ]
