# Generated by Django 5.2.10 on 2026-01-17 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Успешный вход'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('submit', 'Отправка на модерацию'), ('approve', 'Одобрение'), ('reject', 'Отклонение'), ('archive', 'Архивирование'), ('generate', 'AI-генерация')], max_length=16)),
                ('entity_type', models.CharField(choices=[('user', 'Пользователь'), ('card', 'Карточка'), ('scenario', 'Сценарий'), ('ai_generation', 'AI генерация')], max_length=32)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='audit_audit_entity__8eaca5_idx'), models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx')],
            },
        ),
    ]
